# 
# Synthesis run script generated by Vivado
# 

<<<<<<< HEAD
set_param xicom.use_bs_reader 1
=======
>>>>>>> d01a2632b168652a191fcac3f98a1cd72568103e
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
<<<<<<< HEAD
set_property webtalk.parent_dir /home/gjaa.connect/Downloads/ECEN-449-master/lab1/jackpot/jackpot.cache/wt [current_project]
set_property parent.project_path /home/gjaa.connect/Downloads/ECEN-449-master/lab1/jackpot/jackpot.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib /home/gjaa.connect/Downloads/ECEN-449-master/lab1/jackpot/jackpot.srcs/sources_1/new/jackpot.v
read_xdc /home/gjaa.connect/Downloads/ECEN-449-master/lab1/jackpot/jackpot.srcs/constrs_1/new/jackpot.xdc
set_property used_in_implementation false [get_files /home/gjaa.connect/Downloads/ECEN-449-master/lab1/jackpot/jackpot.srcs/constrs_1/new/jackpot.xdc]
=======
set_property webtalk.parent_dir /home/gjaa.connect/ECEN449/lab1/jackpot/jackpot.cache/wt [current_project]
set_property parent.project_path /home/gjaa.connect/ECEN449/lab1/jackpot/jackpot.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib /home/gjaa.connect/ECEN449/lab1/jackpot/jackpot.srcs/sources_1/new/jackpot.v
read_xdc /home/gjaa.connect/ECEN449/lab1/jackpot/jackpot.srcs/constrs_1/new/jackpot.xdc
set_property used_in_implementation false [get_files /home/gjaa.connect/ECEN449/lab1/jackpot/jackpot.srcs/constrs_1/new/jackpot.xdc]
>>>>>>> d01a2632b168652a191fcac3f98a1cd72568103e

synth_design -top jackpot -part xc7z010clg400-1
write_checkpoint -noxdef jackpot.dcp
catch { report_utilization -file jackpot_utilization_synth.rpt -pb jackpot_utilization_synth.pb }
